---
meta:
  password: (( vault $CREDENTIALS "/mongo/users/admin:password" ))

releases:
  - { name: mongo-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: mongod
    instances: 1
    azs: [z1]
    networks:
      - name: mongo-service
    stemcell: default

    vm_type:              (( grab meta.size ))
    persistent_disk_type: default

    jobs:
      - name:    standalone
        release: mongo-forge
        properties:
          debug: true
